app = "pharmabeaver"        
primary_region = "iad"      

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
